### ISSUE TITLE
[Question] Models for sophisticated wolves don't appear

### ISSUE THREAD

**Issue by satoboom** [Ocelot5836/BetterAnimalsOriginal#18]
I have sophisticated wolves enabled, and their regular models appear rather than the models on this mod. Can I please get some help changing the model to the one in this mod?

**Comment by itsmeow** [comment]
Hi, please start the game with BetterAnimals and SophisticatedWolves installed, load to the main menu, exit, and post your latest.log file in .minecraft/logs here.
Also,
What version of the mod are you using? What Minecraft version?

**Comment by satoboom** [comment]
I'm using soph. wolves version 3.13.7 and better animals 3.0, and I use version 1.12.2

> [18:56:28] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:56:28] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:56:28] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[18:56:28] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2771 for Minecraft 1.12.2 loading
[18:56:28] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_51
[18:56:28] [main/INFO] [FML]: Searching C:\Users\ARIANA\AppData\Roaming\.minecraft\mods for mods
[18:56:28] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:56:28] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[18:56:28] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:56:28] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:56:28] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:56:30] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[18:56:30] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[18:56:30] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:56:30] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[18:56:31] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[18:56:31] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[18:56:31] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[18:56:31] [main/INFO] [net.minecraft.client.Minecraft]: Setting user: CobraCorroso
[18:56:35] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: lastServer:
[18:56:35] [main/INFO] [net.minecraft.client.Minecraft]: LWJGL Version: 2.9.4
[18:56:36] [main/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 655426800 bytes (625 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 369.09' Renderer: 'Quadro 600/PCIe/SSE2'
[18:56:36] [main/INFO] [FML]: MinecraftForge v14.23.5.2771 Initialized
[18:56:36] [main/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[18:56:37] [main/INFO] [FML]: Replaced 1036 ore ingredients
[18:56:37] [main/INFO] [FML]: Searching C:\Users\ARIANA\AppData\Roaming\.minecraft\mods for mods
[18:56:38] [main/INFO] [FML]: Forge Mod Loader has identified 6 mods to load
[18:56:38] [main/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, betteranimals, sophisticatedwolves] at CLIENT
[18:56:38] [main/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, betteranimals, sophisticatedwolves] at SERVER
[18:56:39] [Thread-3/INFO] [FML]: Using sync timing. 200 frames of Display.update took 321620522 nanos
[18:56:39] [main/INFO] [net.minecraft.client.resources.SimpleReloadableResourceManager]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Better Animals Mod, FMLFileResourcePack:Sophisticated Wolves
[18:56:39] [main/INFO] [FML]: Processing ObjectHolder annotations
[18:56:39] [main/INFO] [FML]: Found 1180 ObjectHolder annotations
[18:56:39] [main/INFO] [FML]: Identifying ItemStackHolder annotations
[18:56:39] [main/INFO] [FML]: Found 0 ItemStackHolder annotations
[18:56:39] [main/INFO] [FML]: Configured a dormant chunk cache size of 0
[18:56:39] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[18:56:39] [main/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `dogbowlte`, expected `sophisticatedwolves`. This could be a intended override, but in most cases indicates a broken mod.
[18:56:39] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Found status: OUTDATED Target: 14.23.5.2772
[18:56:40] [main/INFO] [FML]: Applying holder lookups
[18:56:40] [main/INFO] [FML]: Holder lookups applied
[18:56:40] [main/INFO] [FML]: Applying holder lookups
[18:56:40] [main/INFO] [FML]: Holder lookups applied
[18:56:40] [main/INFO] [FML]: Applying holder lookups
[18:56:40] [main/INFO] [FML]: Holder lookups applied
[18:56:40] [main/INFO] [FML]: Applying holder lookups
[18:56:40] [main/INFO] [FML]: Holder lookups applied
[18:56:40] [main/INFO] [FML]: Injecting itemstacks
[18:56:40] [main/INFO] [FML]: Itemstack injection complete
[18:56:43] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Starting up SoundSystem...
[18:56:43] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: Initializing LWJGL OpenAL
[18:56:43] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[18:56:44] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: OpenAL initialized.
[18:56:44] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Sound engine started
[18:56:46] [main/INFO] [FML]: Max texture size: 16384
[18:56:48] [main/INFO] [net.minecraft.client.renderer.texture.TextureMap]: Created: 512x512 textures-atlas
[18:56:50] [main/INFO] [FML]: Applying holder lookups
[18:56:50] [main/INFO] [FML]: Holder lookups applied
[18:56:50] [main/INFO] [STDOUT]: [com.ocelot.betteranimals.client.RenderHandler:getInteropProxy:66]: Loading compat classes for mod: sophisticatedwolves
[18:56:50] [main/INFO] [STDOUT]: [com.ocelot.betteranimals.client.RenderHandler:getInteropProxy:70]: Found proxy: com.ocelot.betteranimals.compat.ActiveCompatSophisticatedWolves@559e0607
[18:56:50] [main/INFO] [STDOUT]: [com.ocelot.betteranimals.client.RenderHandler:init:49]: Primal proxy: com.ocelot.betteranimals.compat.InactiveCompatPrimalCore@4fc1f04e
[18:56:50] [main/INFO] [FML]: Injecting itemstacks
[18:56:50] [main/INFO] [FML]: Itemstack injection complete
[18:56:50] [main/INFO] [STDOUT]: [com.ocelot.betteranimals.client.RenderHandler:postinit:57]: SophisticatedWolves proxy: com.ocelot.betteranimals.compat.ActiveCompatSophisticatedWolves@559e0607
[18:56:50] [main/INFO] [STDOUT]: [com.ocelot.betteranimals.compat.CompatUtils:getClassForEntity:21]: Found class class sophisticated_wolves.entity.EntitySophisticatedWolf
[18:56:50] [main/INFO] [STDOUT]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:32]: Retrieved method: public sophisticated_wolves.api.EnumWolfSpecies sophisticated_wolves.entity.EntitySophisticatedWolf.getSpecies()
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: java.lang.NoSuchMethodException: sophisticated_wolves.entity.EntitySophisticatedWolf.getTailRotation()
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at java.lang.Class.getMethod(Class.java:1786)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at com.ocelot.betteranimals.compat.CompatUtils.getMethod(CompatUtils.java:31)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at com.ocelot.betteranimals.compat.ActiveCompatSophisticatedWolves.sophisticatedwolves_register(ActiveCompatSophisticatedWolves.java:21)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at com.ocelot.betteranimals.client.RenderHandler.postinit(RenderHandler.java:59)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at com.ocelot.betteranimals.BetterAnimals.postInit(BetterAnimals.java:39)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[18:56:50] [main/INFO] [STDERR]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:35]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:56:50] [main/INFO] [STDOUT]: [com.ocelot.betteranimals.compat.CompatUtils:getMethod:32]: Retrieved method: public float sophisticated_wolves.entity.EntitySophisticatedWolf.func_70920_v()
[18:56:50] [main/INFO] [FML]: Forge Mod Loader has successfully loaded 6 mods
[18:56:50] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: lastServer:
[18:56:50] [main/INFO] [com.mojang.text2speech.NarratorWindows]: Narrator library for x64 successfully loaded
[18:56:51] [Realms Notification Availability checker #1/INFO] [com.mojang.realmsclient.client.RealmsClient]: Could not authorize you against Realms server: Invalid session id
[18:56:52] [main/INFO] [net.minecraft.client.Minecraft]: Stopping!
[18:56:52] [main/INFO] [net.minecraft.client.audio.SoundManager]: SoundSystem shutting down...
[18:56:52] [main/WARN] [net.minecraft.client.audio.SoundManager]: Author: Paul Lamb, www.paulscode.com

**Comment by itsmeow** [comment]
Looks like a bug with the new sophisticatedwolves updates. I'll have to update the mod.

**Comment by itsmeow** [comment]
Hi, tested with the specific version you are using. Seems to work fine. Try replacing your mod files from both BA and Sophisticated Wolves. Have you adjusted any SophisticatedWolves configs?

**Comment by satoboom** [comment]
> Hi, tested with the specific version you are using. Seems to work fine. Try replacing your mod files from both BA and Sophisticated Wolves. Have you adjusted any SophisticatedWolves configs?

I haven't, mostly because I don't trust myself and i think that I'd mess something up. What should I adjust in the config to make this work?

**Comment by itsmeow** [comment]
Nothing, just making sure you haven't affected it in some way. Does reinstalling work?

**Comment by satoboom** [comment]
> Nothing, just making sure you haven't affected it in some way. Does reinstalling work?

So I removed my mods and only put in the two, and it worked. I have wolf armor, do you think that could be a possible reason for the models not working?

**Comment by itsmeow** [comment]
Yes. Wolf armor does not work with this.

**Comment by satoboom** [comment]
> Yes. Wolf armor does not work with this.

Ohh I feel dumb for not thinking about that. Thank you, I've figured it out!

**Comment by itsmeow** [comment]
-----------
Requesting issued #18 to be closed
-----------
